### ISSUE TITLE
validate.require() won't work well for filter.trim() if data spaced

### ISSUE THREAD

**Issue by reekoheek** [dandean/express-form#26] opened 2011-12-18 11:15 UTC
I used configuration as follows:

``` javascript
var form = require('express-form').configure({
    autoTrim: true, 
    passThrough: true,
    autoLocals: false,
    dataSources: ['body']
});
```

and rules as follows:

``` javascript
form(
  filter('url').trim(),
  validate('url', 'URL').required()
)
```

I'm expecting data will be trimmed first and then the trimmed data will be validated.
When I input spaced string only (ex: '        ' ), it won't goes error (should be error because it is empty string)

I check the code and found at lib/field.js line 35

``` javascript
    property = property.replace(/\[((.)*?)\]/g, ".$1"); // Convert square-bracket to dot notation.

    var value = utils.getProp(property, form) || utils.getProp(property, source);
```

the value to evaluated gotten from "form" (which is the right ones) or if it is empty gotten from "source" (its bad cause, trim will make valid input empty string but you take the original from source to evaluate.

My workaround is:

``` javascript
    property = property.replace(/\[((.)*?)\]/g, ".$1"); // Convert square-bracket to dot notation.

    // REMARK by reekoheek: I disabled utils.getProp(property, source) 
    // and leave it to 'form' alone to validate
    // as I use configuration "passThrough = true"
    // var value = utils.getProp(property, form) || utils.getProp(property, source);
    var value = utils.getProp(property, form);  // || utils.getProp(property, source);
```

I hope it will help you, because it takes me hours to search documentations but cannot found about it :)

**Comment by mjadobson** [comment] 2012-03-24 10:28
Yeah, this is unfortunate.

``` javascript
var value = utils.getProp(property, form) || utils.getProp(property, source);
```

What this is trying to do is to use the source for the first time you do methods on a field. Then, afterwards, use the form object. Obviously, just relying on a falsy value is flawed here.

The way to temporarily fix this is to simply call a field once, so instead of:

``` javascript
form(
  filter('url').trim(),
  validate('url', 'URL').required()
)
```

do this:

``` javascript
form(
  field('url', 'URL').trim().required()
)
```

I think the best way to permanently address this issue is to keep a log of which fields have been called, then use that log to decide whether to use the source or `req.form` value.

**Comment by freewil** [comment] 2013-02-22 05:09
Since this is so old, I'm very tempted to just close this. I was able to reproduce the issue but am reluctant to "fix" it since I'm not sure the use case where you wouldn't just use the chaining as @Sugarstack suggested. Please point out if I am missing something or if there needs to be a documentation update for this issue.

**Closed as completed by freewil** 2013-02-22 05:09 UTC
